# Generated by Django 2.2.7 on 2019-12-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20191226_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='lname',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
