# Generated by Django 2.2.7 on 2019-12-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_tutorial_lname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='part',
            name='order',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
