# Generated by Django 2.2.7 on 2019-12-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_auto_20191226_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='order',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
