# Generated by Django 3.0 on 2019-12-28 14:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_auto_20191228_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
