# Generated by Django 3.0 on 2019-12-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_auto_20191228_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='content',
            field=models.TextField(),
        ),
    ]
