# Generated by Django 3.0 on 2019-12-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_auto_20191228_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['slug']},
        ),
        migrations.RemoveField(
            model_name='part',
            name='order',
        ),
        migrations.AddField(
            model_name='part',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
