# Generated by Django 3.0 on 2019-12-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0011_auto_20191231_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='slug',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
