# Generated by Django 3.0 on 2019-12-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_auto_20191231_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='slug',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
