# Generated by Django 3.0 on 2019-12-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0013_auto_20191231_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
